plugins {
    id 'java'
    id 'application'
}

group = 'org.foxesworld.cge'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    maven {
        name = "GitHubPackages-riccardobl"
        url = uri("https://maven.pkg.github.com/riccardobl/*")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("USERNAME_GITHUB")
            password = project.findProperty("gpr.key") ?: System.getenv("TOKEN_GITHUB")
        }
    }
    maven {
        name = "GitHubPackages-jmePhonon"
        url = uri("https://maven.pkg.github.com/jmePhonon/*")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("USERNAME_GITHUB")
            password = project.findProperty("gpr.key") ?: System.getenv("TOKEN_GITHUB")
        }
    }
}
ext {
    jmeVersion = '3.8.1-stable'
}

dependencies {
    // Основные модули jMonkeyEngine
    implementation "org.jmonkeyengine:jme3-core:$jmeVersion"
    implementation "org.jmonkeyengine:jme3-desktop:$jmeVersion"
    implementation "org.jmonkeyengine:jme3-lwjgl3:$jmeVersion"
    implementation "org.jmonkeyengine:jme3-effects:$jmeVersion"
    implementation files("lib/SkyControl-1.1.0.jar")
    runtimeOnly    "org.jmonkeyengine:jme3-awt-dialogs:$jmeVersion"
    implementation "org.jmonkeyengine:jme3-freetype:3.8.1-stable"


    //implementation  'wf.frk:jme-effekseer-native:0.4'
    implementation (group: 'com.jme3.phonon', name: 'jme_phonon', version: '0.3.7', ext: 'jar', classifier: '')
    implementation  "wf.frk:jme3-bullet-vhacd:1.0.5"
    implementation  "wf.frk:jme_f3b:0.92"

    // GSON для загрузки конфигурации из JSON
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.simsilica:zay-es:1.6.0'

    // Логгирование
    implementation 'org.fusesource.jansi:jansi:2.4.0'
    implementation 'org.slf4j:slf4j-api:2.0.9'
    implementation 'org.apache.logging.log4j:log4j-slf4j2-impl:2.20.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'
    implementation 'org.slf4j:jul-to-slf4j:2.0.0'

    // Физика Minie
    implementation 'com.github.stephengold:Minie:9.0.1'

    // JAR-файлы из каталога libs
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // UI: FlatLaf
    implementation 'com.formdev:flatlaf:3.4.1'
    implementation 'com.formdev:flatlaf-extras:3.4.1' // Доп. темы
}

application {
    mainClass = 'test.Game'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}